UPDATE rawdemotech
SET Name = TRIM(' ' from Name);

UPDATE rawweiss2014
SET Company = TRIM(' ' from Company);

UPDATE rawcomplaintsq12014
SET Name = TRIM(' ' from Name);

UPDATE rawcomplaintsq22014
SET Name = TRIM(' ' from Name);

UPDATE rawcomplaintsq42013
SET Name = TRIM(' ' from Name);

UPDATE rawdemotech
SET Name = 'AMERICAN INTEGRITY INSURANCE COMPANY OF FLORIDA'
WHERE name = 'AMERICAN INTEGRITY INSURANCE COMPANY OF FLORIDA, INC';


UPDATE rawdemotech
SET Name = 'AMERICAN STRATEGIC INSURANCE COMPANY'
WHERE name = 'AMERICAN STRATEGIC INSURANCE CORP';

UPDATE rawweiss2014
SET Company = 'ASI ASSURANCE CORP'
WHERE Company = 'ASI ASR CORP';

UPDATE rawdemotech
SET Name = 'PEOPLES TRUST INSURANCE COMPANY'
WHERE name = E'PEOPLE\'S TRUST INSURANCE COMPANY';

UPDATE rawdemotech
SET Name = 'SOUTHERN FIDELITY INSURANCE COMPANY INC'
WHERE name = 'SOUTHERN FIDELITY INSURANCE COMPANY';

UPDATE rawdemotech
SET Name = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY INC'
WHERE name = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY, INC.';

UPDATE rawdemotech
SET Name = 'ST JOHNS INSURANCE COMPANY INC'
WHERE name = 'ST. JOHNS INSURANCE COMPANY, INC';

UPDATE rawdemotech
SET Name = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE'
WHERE name = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'ST JOHNS INSURANCE COMPANY INC'
WHERE name = 'ST. JOHNS INSURANCE COMPANY, INC.';

UPDATE rawcomplaintsq12014
SET Name = 'PEOPLES TRUST INSURANCE COMPANY'
WHERE name = E'PEOPLE\'S TRUST INSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'FLORIDA FARM BU CASUALTY INSURANCE COMPANY'
WHERE name = 'FLORIDA FARM BUREAU CASUALTY INSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'UNITED SERVICES AUTOMOBILE ASN'
WHERE name = 'UNITED SERVICES AUTOMOBILE ASSOCIATION';

UPDATE rawcomplaintsq12014
SET Name = 'HOMEOWNERS CHOICE PROPERTY AND CASUALTY INSURANCE COMPANY'
WHERE name = 'HOMEOWNERS CHOICE PROPERTY AND CASUALTY INSURANCE COMPANY, INC.';

UPDATE rawcomplaintsq12014
SET Name = 'SOUTHERN FIDELITY INSURANCE COMPANY INC'
WHERE name = 'SOUTHERN FIDELITY INSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE'
WHERE name = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'AMERICAN STRATEGIC INSURANCE COMPANY'
WHERE name = 'AMERICAN STRATEGIC INSURANCE CORP';

UPDATE rawcomplaintsq12014
SET Name = 'PRIVILEGE UNDERWRITERS RECIP EXCH'
WHERE name = 'PRIVILEGE UNDERWRITERS RECIPROCAL EXCHANGE';


UPDATE rawcomplaintsq12014
SET Name = 'CAPITOL PREFERRED INSURANCE COMPANY'
WHERE name = 'CAPITOL PREFERRED INSURANCE COMPANY, INC.';


UPDATE rawcomplaintsq12014
SET Name = 'FIRST LIBERTY INSURANCE CORP'
WHERE name = 'FIRST LIBERTY INSURANCE CORPORATION (THE)';

UPDATE rawcomplaintsq12014
SET Name = 'STILLWATER P AND C INSURANCE COMPANY'
WHERE name = 'STILLWATER PROPERTY AND CASUALTY INSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'AMERICAN HOME ASR COMPANY'
WHERE name = 'AMERICAN HOME ASSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'AMERICAN MODERN INSURANCE COMPANY OF FLORIDA'
WHERE name = 'AMERICAN MODERN INSURANCE COMPANY OF FLORIDA, INC.';

UPDATE rawcomplaintsq12014
SET Name = 'ASSOCIATED INDEMNITY CORP'
WHERE name = 'ASSOCIATED INDEMNITY CORPORATION';

UPDATE rawcomplaintsq12014
SET Name = 'FIREMANS FUND INSURANCE COMPANY'
WHERE name = E'FIREMAN\'S FUND INSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'SOUTHERN-OWNERS INSURANCE COMPANY'
WHERE name = 'SOUTHERN OWNERS INSURANCE COMPANY';

UPDATE rawcomplaintsq12014
SET Name = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY INC'
WHERE name = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY, INC.';

-----------------
UPDATE 
rawcomplaintsq22014
SET Name = 'ST JOHNS INSURANCE COMPANY INC'
WHERE name = 'ST. JOHNS INSURANCE COMPANY, INC.';

UPDATE 
rawcomplaintsq22014
SET Name = 'PEOPLES TRUST INSURANCE COMPANY'
WHERE name = E'PEOPLE\'S TRUST INSURANCE COMPANY';

UPDATE 
rawcomplaintsq22014
SET Name = 'FLORIDA FARM BU CASUALTY INSURANCE COMPANY'
WHERE name = 'FLORIDA FARM BUREAU CASUALTY INSURANCE COMPANY';

UPDATE 
rawcomplaintsq22014
SET Name = 'UNITED SERVICES AUTOMOBILE ASN'
WHERE name = 'UNITED SERVICES AUTOMOBILE ASSOCIATION';

UPDATE 
rawcomplaintsq22014
SET Name = 'HOMEOWNERS CHOICE PROPERTY AND CASUALTY INSURANCE COMPANY'
WHERE name = 'HOMEOWNERS CHOICE PROPERTY AND CASUALTY INSURANCE COMPANY, INC.';

UPDATE 
rawcomplaintsq22014
SET Name = 'SOUTHERN FIDELITY INSURANCE COMPANY INC'
WHERE name = 'SOUTHERN FIDELITY INSURANCE COMPANY';

UPDATE 
rawcomplaintsq22014
SET Name = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE'
WHERE name = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE COMPANY';

UPDATE 
rawcomplaintsq22014
SET Name = 'AMERICAN STRATEGIC INSURANCE COMPANY'
WHERE name = 'AMERICAN STRATEGIC INSURANCE CORP';

UPDATE 
rawcomplaintsq22014
SET Name = 'PRIVILEGE UNDERWRITERS RECIP EXCH'
WHERE name = 'PRIVILEGE UNDERWRITERS RECIPROCAL EXCHANGE';


UPDATE 
rawcomplaintsq22014
SET Name = 'CAPITOL PREFERRED INSURANCE COMPANY'
WHERE name = 'CAPITOL PREFERRED INSURANCE COMPANY, INC.';


UPDATE 
rawcomplaintsq22014
SET Name = 'FIRST LIBERTY INSURANCE CORP'
WHERE name = 'FIRST LIBERTY INSURANCE CORPORATION (THE)';

UPDATE 
rawcomplaintsq22014
SET Name = 'STILLWATER P AND C INSURANCE COMPANY'
WHERE name = 'STILLWATER PROPERTY AND CASUALTY INSURANCE COMPANY';

UPDATE 
rawcomplaintsq22014
SET Name = 'AMERICAN HOME ASR COMPANY'
WHERE name = 'AMERICAN HOME ASSURANCE COMPANY';

UPDATE 
rawcomplaintsq22014
SET Name = 'AMERICAN MODERN INSURANCE COMPANY OF FLORIDA'
WHERE name = 'AMERICAN MODERN INSURANCE COMPANY OF FLORIDA, INC.';

UPDATE 
rawcomplaintsq22014
SET Name = 'ASSOCIATED INDEMNITY CORP'
WHERE name = 'ASSOCIATED INDEMNITY CORPORATION';

UPDATE 
rawcomplaintsq22014
SET Name = 'FIREMANS FUND INSURANCE COMPANY'
WHERE name = E'FIREMAN\'S FUND INSURANCE COMPANY';

UPDATE 
rawcomplaintsq22014
SET Name = 'SOUTHERN-OWNERS INSURANCE COMPANY'
WHERE name = 'SOUTHERN OWNERS INSURANCE COMPANY';

UPDATE 
rawcomplaintsq22014
SET Name = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY INC'
WHERE name = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY, INC.';
-----------------
UPDATE 
rawcomplaintsq42013
SET Name = 'ST JOHNS INSURANCE COMPANY INC'
WHERE name = 'ST. JOHNS INSURANCE COMPANY INC.';

UPDATE 
rawcomplaintsq42013
SET Name = 'PEOPLES TRUST INSURANCE COMPANY'
WHERE name = E'PEOPLE\'S TRUST INSURANCE COMPANY';

UPDATE 
rawcomplaintsq42013
SET Name = 'FLORIDA FARM BU CASUALTY INSURANCE COMPANY'
WHERE name = 'FLORIDA FARM BUREAU CASUALTY INSURANCE COMPANY';

UPDATE 
rawcomplaintsq42013
SET Name = 'UNITED SERVICES AUTOMOBILE ASN'
WHERE name = 'UNITED SERVICES AUTOMOBILE ASSOCIATION';

UPDATE 
rawcomplaintsq42013
SET Name = 'HOMEOWNERS CHOICE PROPERTY AND CASUALTY INSURANCE COMPANY'
WHERE name = 'HOMEOWNERS CHOICE PROPERTY AND CASUALTY INSURANCE COMPANY INC.';

UPDATE 
rawcomplaintsq42013
SET Name = 'SOUTHERN FIDELITY INSURANCE COMPANY INC'
WHERE name = 'SOUTHERN FIDELITY INSURANCE COMPANY';

UPDATE 
rawcomplaintsq42013
SET Name = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE'
WHERE name = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE COMPANY';

UPDATE 
rawcomplaintsq42013
SET Name = 'AMERICAN STRATEGIC INSURANCE COMPANY'
WHERE name = 'AMERICAN STRATEGIC INSURANCE CORP';

UPDATE
rawcomplaintsq42013
SET Name = 'PRIVILEGE UNDERWRITERS RECIP EXCH'
WHERE name = 'PRIVILEGE UNDERWRITERS RECIPROCAL EXCHANGE';


UPDATE 
rawcomplaintsq42013
SET Name = 'CAPITOL PREFERRED INSURANCE COMPANY'
WHERE name = 'CAPITOL PREFERRED INSURANCE COMPANY INC.';


UPDATE 
rawcomplaintsq42013
SET Name = 'FIRST LIBERTY INSURANCE CORP'
WHERE name = 'FIRST LIBERTY INSURANCE CORPORATION (THE)';

UPDATE 
rawcomplaintsq42013
SET Name = 'STILLWATER P AND C INSURANCE COMPANY'
WHERE name = 'STILLWATER PROPERTY AND CASUALTY INSURANCE COMPANY';

UPDATE 
rawcomplaintsq42013
SET Name = 'AMERICAN HOME ASR COMPANY'
WHERE name = 'AMERICAN HOME ASSURANCE COMPANY';

UPDATE 
rawcomplaintsq42013
SET Name = 'AMERICAN MODERN INSURANCE COMPANY OF FLORIDA'
WHERE name = 'AMERICAN MODERN INSURANCE COMPANY OF FLORIDA, INC.';

UPDATE 
rawcomplaintsq42013
SET Name = 'ASSOCIATED INDEMNITY CORP'
WHERE name = 'ASSOCIATED INDEMNITY CORPORATION';

UPDATE 
rawcomplaintsq42013
SET Name = 'FIREMANS FUND INSURANCE COMPANY'
WHERE name = E'FIREMAN\'S FUND INSURANCE COMPANY';

UPDATE 
rawcomplaintsq42013
SET Name = 'SOUTHERN-OWNERS INSURANCE COMPANY'
WHERE name = 'SOUTHERN OWNERS INSURANCE COMPANY';

UPDATE 
rawcomplaintsq42013
SET Name = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY INC'
WHERE name = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY INC.';
---------------
UPDATE rawpolicycount
SET NAME = 'AMERICAN HOME ASR COMPANY'
WHERE NAME = 'AMERICAN HOME ASSURANCE COMPANY';

UPDATE rawpolicycount
SET NAME = 'AMERICAN MODERN INSURANCE COMPANY OF FLORIDA'
WHERE NAME = 'AMERICAN MODERN INSURANCE COMPANY OF FLORIDA, INC';

UPDATE rawpolicycount
SET NAME = 'AMERICAN STRATEGIC INSURANCE COMPANY'
WHERE NAME = 'AMERICAN STRATEGIC INSURANCE CORP';

UPDATE rawpolicycount
SET NAME = 'CAPITOL PREFERRED INSURANCE COMPANY'
WHERE NAME = 'CAPITOL PREFERRED INSURANCE COMPANY, INC';

UPDATE rawpolicycount
SET NAME = 'FIRST LIBERTY INSURANCE CORP'
WHERE NAME = 'FIRST LIBERTY INSURANCE CORP (THE)';

UPDATE rawpolicycount
SET NAME = 'FLORIDA FARM BU CASUALTY INSURANCE COMPANY'
WHERE NAME = 'FLORIDA FARM BUREAU CASUALTY INSURANCE COMPANY';

UPDATE rawpolicycount
SET NAME = 'HOMEOWNERS CHOICE PROPERTY AND CASUALTY INSURANCE COMPANY'
WHERE NAME = 'HOMEOWNERS CHOICE PROPERTY AND CASUALTY INSURANCE COMPANY, INC';

UPDATE rawpolicycount
SET NAME = 'PRIVILEGE UNDERWRITERS RECIP EXCH'
WHERE NAME = 'PRIVILEGE UNDERWRITERS RECIPROCAL EXCHANGE';

UPDATE rawpolicycount
SET NAME = 'SOUTHERN FIDELITY INSURANCE COMPANY INC'
WHERE NAME = 'SOUTHERN FIDELITY INSURANCE COMPANY';

UPDATE rawpolicycount
SET NAME = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY INC'
WHERE NAME = 'SOUTHERN FIDELITY PROPERTY AND CASUALTY, INC';

UPDATE rawpolicycount
SET NAME = 'ST JOHNS INSURANCE COMPANY INC'
WHERE NAME = 'ST JOHNS INSURANCE COMPANY, INC';

UPDATE rawpolicycount
SET NAME = 'STILLWATER P AND C INSURANCE COMPANY'
WHERE NAME = 'STILLWATER PROPERTY AND CASUALTY INSURANCE COMPANY';

UPDATE rawpolicycount
SET NAME = 'TOWER HILL PREFERRED INSURANCE COMPANY'
WHERE NAME = 'TOWER HILL PREFERRED INSURANCE COMPANY ';

UPDATE rawpolicycount
SET NAME = 'UNITED SERVICES AUTOMOBILE ASN'
WHERE NAME = 'UNITED SERVICES AUTOMOBILE ASSOCIATION';

UPDATE rawpolicycount
SET NAME = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE'
WHERE NAME = 'UNIVERSAL PROPERTY AND CASUALTY INSURANCE COMPANY';
---------------------------