CREATE OR REPLACE FUNCTION FX_GetAvg (
	ValueARR INTEGER[]
)
RETURNS NUMERIC AS $$
DECLARE _SUM NUMERIC;
DECLARE _COUNT INTEGER;
DECLARE V NUMERIC;
BEGIN
	_SUM := 0;
	_COUNT := 0;
	FOREACH V IN ARRAY ValueARR
	LOOP
		IF(V IS NOT NULL) THEN
		_SUM := _SUM + V;
		_COUNT := _COUNT + 1;

	RAISE NOTICE 'CURENT VALUE: %',V;		
RAISE NOTICE 'CURENT SUM: %',_SUM;
		END IF;
	END LOOP;
	IF (_COUNT = 0) THEN
		RETURN NULL;
	END IF;
	RETURN (_SUM/_COUNT)::NUMERIC;
END;
$$ LANGUAGE plpgsql;