CREATE OR REPLACE FUNCTION FX_GetSum (
	ValueARR INTEGER[]
)
RETURNS INTEGER AS $$
DECLARE _SUM INTEGER;
DECLARE _COUNT INTEGER;
DECLARE V INTEGER;
BEGIN
	_SUM := 0;
	_COUNT := 0;
	FOREACH V IN ARRAY ValueARR
	LOOP
		IF(V IS NOT NULL) THEN
		_SUM := _SUM + V;
		_COUNT := _COUNT + 1;
		END IF;
	END LOOP;
	IF (_COUNT = 0) THEN
		RETURN NULL;
	END IF;
	RETURN _SUM;
END;
$$ LANGUAGE plpgsql;